name: Lint
on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer install --no-progress
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --no-progress

  php_cs_fixer:
    name: PHP-CS-Fxier Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer install --no-progress
    - name: Run PHP-CS-Fxier
      run: ./vendor/bin/php-cs-fixer fix --dry-run --diff 1>&2
  
  php_cs_fixer_auto_fix:
    name: PHP-CS-Fxier Fix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer install --no-progress
    - name: Run PHP-CS-Fxier
      run: ./vendor/bin/php-cs-fixer fix --diff 1>&2
    - name: Commit Changes
      run: |
        git config user.email "nauxliu@gmail.com"
        git config user.name "GitHub Action"
        git add -A
        git commit -m 'Fix code style' --allow-empty
        git push -u origin HEAD
